### ISSUE TITLE
Configure a default system prompt for a chain

### ISSUE THREAD

**Issue by OskarStark** [php-llm/llm-chain#171]
This could look like this in the bundle:
```yaml
    chain:
        default:
            platform: 'llm_chain.platform.azure.default'
            model:
                name: 'GPT'
                version: 'gpt-4o'
                options:
                    temperature: 0.8
            tools: false
            system_prompt: |
                You are a helpful assistant.
                You are here to provide information and help users find the information they need.
                You are polite and professional, and you always provide accurate information.
```
