### ISSUE TITLE
Examples as E2E Tests

### ISSUE THREAD

**Issue by chr-hertel** [php-llm/llm-chain#32]
Would be interesting to run the examples as E2E tests. Would require tokens (not that problematic with secrets i guess) but also a clever way to execute and run assertions.

Maybe it's enough to have a proper exit code? :thinking:

**Comment by OskarStark** [comment]
What about prompting "Answer just with: OK" or a structured output?

**Comment by chr-hertel** [comment]
> Answer just with: OK

Huh, easy one - i Like 👍

**Comment by chr-hertel** [comment]
after integrating the example runner, this is not that urgent anymore, but basically that thing could be converted to a functional phpunit test - only important to execute those example parallel not sequentially

**Comment by OskarStark** [comment]
@OskarStark asked me to share some ideas for implementing examples as E2E tests. Here are several approaches that could work:

## 1. PHPUnit Integration with Data Providers

```php
<?php

namespace PhpLlm\LlmChain\Tests\E2E;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Process\Process;

class ExamplesE2ETest extends TestCase
{
    /**
     * @dataProvider exampleProvider
     */
    public function testExample(string $examplePath, string $expectedOutput = 'OK'): void
    {
        $process = new Process(['php', $examplePath]);
        $process->run();
        
        $this->assertTrue($process->isSuccessful());
        $this->assertStringContainsString($expectedOutput, $process->getOutput());
    }
    
    public function exampleProvider(): array
    {
        return [
            'openai-chat' => ['examples/openai/chat.php'],
            'anthropic-chat' => ['examples/anthropic/chat.php'],
            // ...
        ];
    }
}
```

## 2. Structured Output for Deterministic Tests

Add a test mode to each example:

```php
// In examples/openai/chat.php
if (getenv('E2E_TEST_MODE')) {
    $messages = new MessageBag(
        Message::forSystem('You are a test bot. Always respond with exactly: {"status": "OK", "model": "gpt-4"}'),
        Message::ofUser('Test message')
    );
    
    $response = $chain->call($messages, ['output_structure' => TestResponse::class]);
    
    echo json_encode($response->getContent());
    exit($response->getContent()->status === 'OK' ? 0 : 1);
}
```

## 3. Mock Platform for Tests

Create a test platform that provides deterministic responses:

```php
class MockPlatform implements PlatformInterface
{
    private array $responses = [];
    
    public function addResponse(string $modelClass, ResponseInterface $response): void
    {
        $this->responses[$modelClass] = $response;
    }
    
    public function request(ModelInterface $model, $input, array $options = []): ResponseInterface
    {
        return $this->responses[get_class($model)] 
            ?? new TextResponse('{"status": "OK"}');
    }
}
```

## 4. GitHub Actions Matrix for Parallel Execution

```yaml
name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        example:
          - openai/chat
          - anthropic/chat
          - google/chat
          # ...
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run E2E Test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          E2E_TEST_MODE: true
        run: |
          php examples/${{ matrix.example }}.php
```

## 5. Assertion Helper for Examples

A small helper class for the examples:

```php
class E2ETestHelper
{
    public static function assertAndExit(Chain $chain, MessageBag $messages): void
    {
        if (\!getenv('E2E_TEST_MODE')) {
            return;
        }
        
        try {
            $response = $chain->call($messages, [
                'temperature' => 0, // Deterministic
                'max_tokens' => 10,
            ]);
            
            $content = $response->getContent();
            $success = str_contains(strtolower($content), 'ok');
            
            echo $success ? "E2E Test: PASSED\n" : "E2E Test: FAILED\n";
            exit($success ? 0 : 1);
            
        } catch (\Throwable $e) {
            echo "E2E Test: ERROR - " . $e->getMessage() . "\n";
            exit(1);
        }
    }
}
```

## Recommendation

The most elegant solution would probably be a combination of:
- Structured Output for deterministic responses (as @OskarStark suggested)
- PHPUnit with Data Providers for test organization
- GitHub Actions Matrix for parallel execution
- Environment variable `E2E_TEST_MODE` to distinguish between normal and test mode

This approach would:
- Keep examples runnable as standalone scripts
- Allow systematic testing with proper assertions
- Enable parallel execution in CI
- Minimize API token usage through deterministic prompts

What do you think?

🤖 This comment was generated by Claude at @OskarStark's request
